language: ruby
rvm:
  - ruby-1.9.3-p484

before_script:
  - RAILS_ENV=test

notifications:
  email: false

cache:
  - bundler

addons:
  code_climate:
    repo_token: 64b799e04ad992db634a81a8138e227dfa556f466572258c5720d3c6a4fa0fc6

script: "bundle exec rspec --format progress"
